name: mrbgem-template
version: "0.3.0"
summary: mrbgems template generator
description: |
  mrbgems template generator

base: core18
license: MIT

confinement: strict

layout:
  /usr/local/mruby-mrbgems:
    bind: $SNAP_COMMON/usr/local/mruby-mrbgems

parts:
  mrbgem-template:
    source: https://github.com/udzura/mruby-mrbgem-template.git
    plugin: make
    build-packages:
      - libruby2.5
      - ruby2.5
      - ruby2.5-dev
      - rake
      - gcc
      - bison
    stage-packages:
      - git
    artifacts:
      - mruby/bin/mrbgem-template
apps:
  mrbgem-template:
    command: mruby/bin/mrbgem-template